obj-$(CONFIG_OPLUS_FEATURE_SCHED_ASSIST) += sched_assist_common.o sched_assist_mutex.o sched_assist_rwsem.o sched_assist_futex.o sched_assist_workqueue.o
obj-$(CONFIG_LOCKING_PROTECT) += sched_assist_locking.o
